### ISSUE TITLE
Panic when using ParentSync

### ISSUE THREAD

**Issue by jonastar** [lifescapegame/bevy_replicon#44]
The following test will sometimes cause a panic:

```rust

#[test]
fn despawn_replication_hierarchy() {
    let mut server_app = App::new();
    let mut client_app = App::new();
    for app in [&mut server_app, &mut client_app] {
        app.add_plugins((
            MinimalPlugins,
            ReplicationPlugins.set(ServerPlugin::new(TickPolicy::Manual)),
        ))
        .replicate::<TableComponent>();
    }

    common::connect(&mut server_app, &mut client_app);

    let server_entity = server_app.world.spawn((Replication, TableComponent)).id();

    server_app.add_systems(
        Update,
        move |mut commands: Commands, mut has_run: Local<bool>| {
            if *has_run {
                return;
            }
            *has_run = true;

            // Should be inserted in `Update` to avoid sync in `PreUpdate`.
            commands.entity(server_entity).with_children(|parent| {
                parent.spawn((Replication, ParentSync::default()));
            });
        },
    );

    server_app.update();
    client_app.update();

    let client_entities = client_app
        .world
        .query_filtered::<Entity, With<Replication>>()
        .iter(&client_app.world)
        .count();

    let client_entities_with_parent = client_app
        .world
        .query_filtered::<Entity, (With<Replication>, With<Parent>)>()
        .iter(&client_app.world)
        .count();

    assert_eq!(client_entities, 2);
    assert_eq!(client_entities_with_parent, 1);

    despawn_with_children_recursive(&mut server_app.world, server_entity);

    server_app.update();
    client_app.update();

    let entity_map = client_app.world.resource::<NetworkEntityMap>();
    assert!(entity_map.to_client().is_empty());
    assert!(entity_map.to_server().is_empty());
}
```

This is the panic backtrace:

```
thread 'despawn_replication_hierarchy' panicked at 'Entity 1v0 does not exist', src/replicon_core.rs:394:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: bevy_ecs::world::World::entity_mut::panic_no_entity
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:285:13
   3: bevy_ecs::world::World::entity_mut
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:290:21
   4: bevy_replicon::replicon_core::WorldDiff::deserialize_to_world::{{closure}}::{{closure}}
             at ./src/replicon_core.rs:394:25
   5: bevy_ecs::world::World::resource_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1344:22
   6: bevy_replicon::replicon_core::WorldDiff::deserialize_to_world::{{closure}}
             at ./src/replicon_core.rs:363:13
   7: bevy_ecs::world::World::resource_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1344:22
   8: bevy_replicon::replicon_core::WorldDiff::deserialize_to_world
             at ./src/replicon_core.rs:362:9
   9: bevy_replicon::client::ClientPlugin::diff_receiving_system::{{closure}}
             at ./src/client.rs:51:17
  10: bevy_ecs::world::World::resource_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1344:22
  11: bevy_replicon::client::ClientPlugin::diff_receiving_system
             at ./src/client.rs:49:9
  12: core::ops::function::FnMut::call_mut
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:166:5
  13: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:294:13
  14: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn() .> Out>>::run::call_inner
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/exclusive_function_system.rs:203:21
  15: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn() .> Out>>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/exclusive_function_system.rs:206:17
  16: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/exclusive_function_system.rs:103:19
  17: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_exclusive_system_task::{{closure}}::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/executor/multi_threaded.rs:592:21
  18: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  21: __rust_try
  22: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  23: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  24: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_exclusive_system_task::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/executor/multi_threaded.rs:591:27
  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:296:9
  26: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  27: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  28: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  29: __rust_try
  30: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  31: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  32: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  33: async_executor::Executor::spawn::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.1/src/lib.rs:145:20
  34: async_task::raw::RawTask<F,T,S,M>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
  35: async_task::runnable::Runnable<M>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18
  36: async_executor::Executor::tick::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.1/src/lib.rs:210:9
  37: bevy_tasks::thread_executor::ThreadExecutorTicker::tick::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/thread_executor.rs:105:39
  38: bevy_tasks::task_pool::TaskPool::execute_scope::{{closure}}::{{closure}}::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:503:45
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:296:9
  40: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  41: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  42: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  43: __rust_try
  44: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  45: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  46: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  47: bevy_tasks::task_pool::TaskPool::execute_scope::{{closure}}::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:506:77
  48: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:526:33
  49: bevy_tasks::task_pool::TaskPool::execute_scope::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:509:41
  50: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:420:85
  51: futures_lite::future::block_on::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:89:27
  52: std::thread::local::LocalKey<T>::try_with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/local.rs:270:16
  53: std::thread::local::LocalKey<T>::with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/local.rs:246:9
  54: futures_lite::future::block_on
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:79:5
  55: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:374:13
  56: bevy_tasks::task_pool::TaskPool::scope_with_executor::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:318:17
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/local.rs:270:16
  58: std::thread::local::LocalKey<T>::with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/local.rs:246:9
  59: bevy_tasks::task_pool::TaskPool::scope_with_executor
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.2/src/task_pool.rs:307:9
  60: <bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/executor/multi_threaded.rs:190:9
  61: bevy_ecs::schedule::schedule::Schedule::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/schedule.rs:235:9
  62: bevy_ecs::world::World::try_run_schedule::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1851:55
  63: bevy_ecs::world::World::try_schedule_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1782:21
  64: bevy_ecs::world::World::try_run_schedule
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1851:9
  65: bevy_app::main_schedule::Main::run_main::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.2/src/main_schedule.rs:146:25
  66: bevy_ecs::world::World::resource_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1344:22
  67: bevy_app::main_schedule::Main::run_main
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.2/src/main_schedule.rs:144:9
  68: core::ops::function::FnMut::call_mut
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:166:5
  69: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:294:13
  70: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run::call_inner
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/exclusive_function_system.rs:203:21
  71: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/exclusive_function_system.rs:206:17
  72: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/exclusive_function_system.rs:103:19
  73: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/executor/single_threaded.rs:98:21
  74: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  77: __rust_try
  78: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  79: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  80: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/executor/single_threaded.rs:97:27
  81: bevy_ecs::schedule::schedule::Schedule::run
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/schedule/schedule.rs:235:9
  82: bevy_ecs::world::World::run_schedule::{{closure}}
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1865:51
  83: bevy_ecs::world::World::try_schedule_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1782:21
  84: bevy_ecs::world::World::schedule_scope
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1836:9
  85: bevy_ecs::world::World::run_schedule
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/world/mod.rs:1865:9
  86: bevy_app::app::App::update
             at /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.2/src/app.rs:244:13
  87: replication::despawn_replication_hierarchy
             at ./tests/replication.rs:288:5
  88: replication::despawn_replication_hierarchy::{{closure}}
             at ./tests/replication.rs:237:36
  89: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  90: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
```

**Comment by jonastar** [comment]
> Does this panic occur on master?

Yup

**Comment by Shatur** [comment]
@jonastar I can't reproduce it on my machine, but we did a huge rework of the part that causes panic in 0c681da851dbd0a5d778e1758ab35bd020d577ac. Could you please try it again and see if the issue is still exists?

**Comment by jonastar** [comment]
> @jonastar I can't reproduce it on my machine, but we did a huge rework of the part that causes panic in [0c681da](https://github.com/lifescapegame/bevy_replicon/commit/0c681da851dbd0a5d778e1758ab35bd020d577ac). Could you please try it again and see if the issue is still exists?

It still triggers for me, the test I provided is sporadic so you might have to run it a few times before it triggers.

**Comment by Shatur** [comment]
I should have read the description more carefully, I thought that one of the existing tests was failing.
Reproduced and fixed!
Thank you, I love it when people send test cases. But I decided to correct current despawning test since it already touches hierarchy.
